version: 2
updates:
  # Daily updates for NuGet packages
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    groups:
      DataPLANT:
        patterns:
          - "ARCtrl*"
          - "FSSpreadsheet*"
          - "DynamicObj*"
          - "ARCTokenization*"
          - "ControlledVocabulary*"
          - "ARCExpect*"
          - "ARCValidationPackages*"
          - "AVPRClient*"
          - "AVPRIndex*"
        labels:
          - "Dependency: DataPLANT"
      Tests:
        patterns:
          - "xunit*"
          - "Expecto*"
          - "Fable.Pyxpecto*"
        labels:
          - "Dependency: Tests"
      Fable:
        patterns:
          - "Fable*"
        labels:
          - "Dependency: Fable"
      Other:
        exclude-patterns:
          - "ARCtrl*"
          - "FSSpreadsheet*"
          - "DynamicObj*"
          - "ARCTokenization*"
          - "ControlledVocabulary*"
          - "ARCExpect*"
          - "ARCValidationPackages*"
          - "AVPRClient*"
          - "AVPRIndex*"
          - "xunit*"
          - "Expecto*"
          - "Fable.Pyxpecto*"
        labels:
          - "Dependency: Other"
  
  # Weekly updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "Dependency: github actions"
