version: 2
updates:
  # Daily updates for a specific group of NuGet packages
  - package-ecosystem: nuget
    directory: "/src/arc-export/"
    schedule:
      interval: daily
    # Create a group of dependencies to be updated together in one pull request
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      ARCtrl:
        patterns:
          - "ARCtrl*"
      Other:
        exclude-patterns:
          - "ARCtrl*"
  
  # Weekly updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/src/arc-export/"
    schedule:
      interval: weekly
