version: 2
updates:
  # Daily updates for a specific group of NuGet packages
  - package-ecosystem: nuget
    directory: "/src/arc-export/"
    schedule:
      interval: daily
    allow:
      - dependency-name: 
          # List your specific NuGet packages here
          - ARCtrl*

  # Weekly updates for all other NuGet packages
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name:
          # Exclude the packages already covered by the daily updates
          - ARCtrl*

  # Weekly updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/src/arc-export/"
    schedule:
      interval: weekly
